# Generated by Django 5.2.18 on 2026-10-10 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0033_indexrun_reindex_documents"),
        ("rag", "0004_include_patterns_images"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "prefix",
                    models.CharField(
                        editable=False, max_length=16, unique=True, verbose_name="Präfix"
                    ),
                ),
                ("key_hash", models.CharField(editable=False, max_length=64, verbose_name="Hash")),
                ("scopes", models.JSONField(blank=True, default=list, verbose_name="Rechte")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="läuft ab"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="widerrufen"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="zuletzt benutzt"),
                ),
                (
                    "last_used_ip",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="zuletzt von"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="erstellt")),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="chat.collection",
                        verbose_name="erlaubte Sammlungen",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Konto",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="rag.directorysource",
                        verbose_name="erlaubte Verzeichnisquellen",
                    ),
                ),
                (
                    "tool_conversation",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.conversation",
                        verbose_name="Chat für Werkzeugaufrufe",
                    ),
                ),
            ],
            options={
                "verbose_name": "API-Key",
                "verbose_name_plural": "API-Keys",
                "ordering": ["-created", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ApiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=50, verbose_name="Methode")),
                ("tool", models.CharField(blank=True, max_length=100, verbose_name="Werkzeug")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "erfolgreich"),
                            ("tool_error", "Werkzeug meldet Fehler"),
                            ("denied", "nicht erlaubt"),
                            ("invalid", "ungültige Anfrage"),
                            ("unauthorized", "Key ungültig"),
                            ("rate_limited", "gedrosselt"),
                            ("error", "interner Fehler"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(default=200, verbose_name="HTTP-Status"),
                ),
                ("duration_ms", models.PositiveIntegerField(default=0, verbose_name="Dauer (ms)")),
                (
                    "request_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="Anfrage (Bytes)"),
                ),
                (
                    "response_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="Antwort (Bytes)"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-Adresse"),
                ),
                (
                    "created",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Zeit"),
                ),
                (
                    "key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="node.apikey",
                        verbose_name="API-Key",
                    ),
                ),
            ],
            options={
                "verbose_name": "API-Aufruf",
                "verbose_name_plural": "API-Aufrufe",
                "ordering": ["-created", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationOverview",
            fields=[],
            options={
                "verbose_name": "Integrationen",
                "verbose_name_plural": "Integrationen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("node.apikey",),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["owner", "active"], name="node_apikey_owner_active"),
        ),
        migrations.AddIndex(
            model_name="apicall",
            index=models.Index(fields=["key", "created"], name="node_apicall_key_created"),
        ),
        migrations.AddIndex(
            model_name="apicall",
            index=models.Index(fields=["ip", "status", "created"], name="node_apicall_ip_status"),
        ),
        migrations.AddIndex(
            model_name="apicall",
            index=models.Index(fields=["created"], name="node_apicall_created"),
        ),
    ]
