# Generated by Django 5.2.18 on 2026-10-10 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicall",
            name="key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calls",
                to="node.apikey",
                verbose_name="API-Key",
            ),
        ),
    ]
