# Generated by Django 5.2.18 on 2026-10-09 14:58

import django.db.models.deletion
from django.db import migrations, models

import multigpt.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0001_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("openai_compat", "OpenAI-kompatibel"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google"),
                        ],
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Leer lassen für die Standard-URL des Anbieters. LM Studio z. B. http://pc.local:1234/v1",
                        max_length=500,
                        verbose_name="Basis-URL",
                    ),
                ),
                (
                    "api_key",
                    multigpt.core.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Wird verschlüsselt gespeichert. Für LM Studio nicht nötig.",
                        verbose_name="API-Key",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "is_local",
                    models.BooleanField(
                        default=False,
                        help_text="Läuft im Intranet (z. B. LM Studio), kostet nichts.",
                        verbose_name="lokal",
                    ),
                ),
                (
                    "check_status",
                    models.BooleanField(
                        default=False,
                        help_text="Für Anbieter, die nicht immer erreichbar sind (Plan 8a).",
                        verbose_name="Online-Status prüfen",
                    ),
                ),
                (
                    "last_online",
                    models.DateTimeField(blank=True, null=True, verbose_name="zuletzt online"),
                ),
            ],
            options={
                "verbose_name": "Anbieter",
                "verbose_name_plural": "Anbieter",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="McpServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("stdio", "stdio (lokaler Prozess)"),
                            ("http", "HTTP (Streamable HTTP)"),
                        ],
                        max_length=10,
                        verbose_name="Transport",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        blank=True,
                        help_text="Nur bei stdio: Programm mit Argumenten.",
                        max_length=500,
                        verbose_name="Befehl",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="Nur bei HTTP.", max_length=500, verbose_name="URL"
                    ),
                ),
                (
                    "credentials",
                    multigpt.core.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Wird verschlüsselt gespeichert, z. B. Token oder JSON mit Umgebungsvariablen.",
                        verbose_name="Zugangsdaten",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "tools_requiring_confirmation",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste der Werkzeugnamen, die erst nach Bestätigung ausgeführt werden.",
                        verbose_name="Werkzeuge mit Rückfrage",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP-Server",
                "verbose_name_plural": "MCP-Server",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("transport", "stdio"), models.Q(("command", ""), _negated=True)
                            ),
                            models.Q(("transport", "http"), models.Q(("url", ""), _negated=True)),
                            _connector="OR",
                        ),
                        name="chat_mcpserver_command_or_url",
                        violation_error_message="stdio braucht einen Befehl, HTTP eine URL.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="Bezeichnung beim Anbieter, z. B. gpt-4o",
                        max_length=200,
                        verbose_name="Modell-ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=200, verbose_name="Anzeigename")),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("image", "Bild"),
                            ("embedding", "Embedding"),
                            ("stt", "Spracherkennung"),
                            ("tts", "Sprachausgabe"),
                        ],
                        default="chat",
                        max_length=20,
                        verbose_name="Fähigkeit",
                    ),
                ),
                (
                    "supports_tools",
                    models.BooleanField(default=False, verbose_name="unterstützt Werkzeuge"),
                ),
                (
                    "can_edit_images",
                    models.BooleanField(default=False, verbose_name="kann Bilder bearbeiten"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="aktiv")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Reihenfolge")),
                (
                    "price_in",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Euro je 1 Mio. Eingabe-Tokens (Bildmodelle: je Bild).",
                        max_digits=12,
                        null=True,
                        verbose_name="Preis Eingabe",
                    ),
                ),
                (
                    "price_out",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Euro je 1 Mio. Ausgabe-Tokens.",
                        max_digits=12,
                        null=True,
                        verbose_name="Preis Ausgabe",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_models",
                        to="chat.provider",
                        verbose_name="Anbieter",
                    ),
                ),
            ],
            options={
                "verbose_name": "KI-Modell",
                "verbose_name_plural": "KI-Modelle",
                "ordering": ["sort_order", "display_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "model_id"),
                        name="chat_aimodel_unique_provider_model_id",
                    )
                ],
            },
        ),
    ]
