# Generated by Django 5.2.18 on 2026-10-09 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import multigpt.chat.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("chat", "0002_provider_aimodel_mcpserver"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="erstellt")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Besitzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sammlung",
                "verbose_name_plural": "Sammlungen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Titel")),
                ("system_prompt", models.TextField(blank=True, verbose_name="System-Prompt")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="erstellt")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="geändert")),
                ("archived", models.BooleanField(default=False, verbose_name="archiviert")),
                (
                    "default_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.aimodel",
                        verbose_name="Standardmodell",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "ordering": ["-updated"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=multigpt.chat.models.document_upload_to,
                        verbose_name="Datei",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "wartet"),
                            ("indexed", "indexiert"),
                            ("error", "Fehler"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("error_text", models.TextField(blank=True, verbose_name="Fehlertext")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="hochgeladen")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="chat.collection",
                        verbose_name="Sammlung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumente",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("index_document", "Dokument indexieren")],
                        max_length=50,
                        verbose_name="Art",
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Daten")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "wartet"),
                            ("running", "läuft"),
                            ("done", "erledigt"),
                            ("failed", "fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0, verbose_name="Versuche")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="erstellt")),
            ],
            options={
                "verbose_name": "Hintergrundjob",
                "verbose_name_plural": "Hintergrundjobs",
                "ordering": ["created", "id"],
                "indexes": [
                    models.Index(fields=["status", "created"], name="chat_job_status_created")
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Nutzer"),
                            ("assistant", "Assistent"),
                            ("system", "System"),
                            ("tool", "Werkzeug"),
                        ],
                        max_length=20,
                        verbose_name="Rolle",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Inhalt")),
                (
                    "tokens_in",
                    models.PositiveIntegerField(default=0, verbose_name="Tokens Eingabe"),
                ),
                (
                    "tokens_out",
                    models.PositiveIntegerField(default=0, verbose_name="Tokens Ausgabe"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Euro, festgehalten zum Zeitpunkt der Antwort.",
                        max_digits=12,
                        null=True,
                        verbose_name="Kosten",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "vollständig"),
                            ("aborted", "abgebrochen"),
                            ("error", "Fehler"),
                        ],
                        default="complete",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="Fehlertext")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="erstellt")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                        verbose_name="Chat",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="chat.aimodel",
                        verbose_name="Modell",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nachricht",
                "verbose_name_plural": "Nachrichten",
                "ordering": ["created", "id"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Bild"), ("audio", "Audio"), ("file", "Datei")],
                        max_length=10,
                        verbose_name="Art",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=multigpt.chat.models.attachment_upload_to,
                        verbose_name="Datei",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Euro, festgehalten zum Zeitpunkt der Erzeugung.",
                        max_digits=12,
                        null=True,
                        verbose_name="Kosten",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="erstellt")),
                (
                    "generated_by_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.aimodel",
                        verbose_name="erzeugt von",
                    ),
                ),
                (
                    "source_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived",
                        to="chat.attachment",
                        verbose_name="Ausgangsbild",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.message",
                        verbose_name="Nachricht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anhang",
                "verbose_name_plural": "Anhänge",
                "ordering": ["created", "id"],
            },
        ),
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("system_prompt", models.TextField(verbose_name="System-Prompt")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vorlage",
                "verbose_name_plural": "Vorlagen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("can_write", models.BooleanField(default=False, verbose_name="Schreibrecht")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="erstellt")),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="chat.collection",
                        verbose_name="Sammlung",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="chat.conversation",
                        verbose_name="Chat",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="accounts.usergroup",
                        verbose_name="Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Freigabe",
                "verbose_name_plural": "Freigaben",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SourceRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("web", "Webseite"), ("document", "Dokument")],
                        max_length=10,
                        verbose_name="Art",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, verbose_name="Titel")),
                ("url", models.URLField(blank=True, max_length=2000, verbose_name="URL")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="chat.message",
                        verbose_name="Nachricht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quelle",
                "verbose_name_plural": "Quellen",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tool", models.CharField(max_length=200, verbose_name="Werkzeug")),
                ("arguments", models.JSONField(blank=True, default=dict, verbose_name="Argumente")),
                ("result", models.JSONField(blank=True, null=True, verbose_name="Ergebnis")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_confirmation", "wartet auf Bestätigung"),
                            ("rejected", "abgelehnt"),
                            ("running", "läuft"),
                            ("ok", "erfolgreich"),
                            ("error", "Fehler"),
                            ("timeout", "Zeitüberschreitung"),
                        ],
                        default="running",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True, verbose_name="Dauer")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="erstellt")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="chat.message",
                        verbose_name="Nachricht",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_calls",
                        to="chat.mcpserver",
                        verbose_name="MCP-Server",
                    ),
                ),
            ],
            options={
                "verbose_name": "Werkzeugaufruf",
                "verbose_name_plural": "Werkzeugaufrufe",
                "ordering": ["created", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="chat_collection_unique_owner_name"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "archived", "-updated"], name="chat_conv_user_updated"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "created"], name="chat_msg_conv_created"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["model", "created"], name="chat_msg_model_created"),
        ),
        migrations.AddConstraint(
            model_name="preset",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="chat_preset_unique_user_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("conversation__isnull", False), ("collection__isnull", True)),
                    models.Q(("conversation__isnull", True), ("collection__isnull", False)),
                    _connector="OR",
                ),
                name="chat_share_exactly_one_target",
                violation_error_message="Freigabe gilt genau einem Chat oder einer Sammlung.",
            ),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.UniqueConstraint(
                condition=models.Q(("conversation__isnull", False)),
                fields=("conversation", "group"),
                name="chat_share_unique_conversation_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.UniqueConstraint(
                condition=models.Q(("collection__isnull", False)),
                fields=("collection", "group"),
                name="chat_share_unique_collection_group",
            ),
        ),
    ]
