# Generated by Django 5.2.18 on 2026-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_conversations_collections_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "vollständig"),
                    ("aborted", "abgebrochen"),
                    ("error", "Fehler"),
                    ("superseded", "ersetzt"),
                ],
                default="complete",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
