# Generated by Django 5.2.18 on 2026-10-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_message_status_superseded"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="last_checked",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="zuletzt geprüft"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="online",
            field=models.BooleanField(default=False, editable=False, verbose_name="online"),
        ),
        migrations.AddField(
            model_name="provider",
            name="reported_models",
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text="Modell-IDs, die der Anbieter bei der letzten Prüfung gemeldet hat.",
                verbose_name="gemeldete Modelle",
            ),
        ),
    ]
