# Generated by Django 5.2.18 on 2026-10-09 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_provider_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="known_tools",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Vom Verwalter eingestufte Werkzeugnamen. Werkzeuge, die hier fehlen, gelten als neu und laufen nur nach Bestätigung.",
                verbose_name="eingestufte Werkzeuge",
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="timeout_seconds",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Höchstdauer je Werkzeugaufruf in Sekunden.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(600),
                ],
                verbose_name="Zeitlimit (s)",
            ),
        ),
        migrations.AddField(
            model_name="toolcall",
            name="provider_call_id",
            field=models.CharField(
                blank=True,
                help_text="Kennung des Werkzeugaufrufs beim KI-Anbieter (ordnet das Ergebnis zu).",
                max_length=200,
                verbose_name="Aufruf-ID des Anbieters",
            ),
        ),
    ]
