# Generated by Django 5.2.18 on 2026-10-09 16:27

import django.db.models.deletion
from django.db import migrations, models

import multigpt.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_mcp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="tool_call",
            field=models.ForeignKey(
                blank=True,
                help_text="Werkzeugaufruf, der diese Datei geliefert hat (Plan 8g).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="chat.toolcall",
                verbose_name="Werkzeugaufruf",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="tool_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                encoder=multigpt.core.fields.UnicodeJSONEncoder,
                verbose_name="Werkzeugzustand",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "vollständig"),
                    ("aborted", "abgebrochen"),
                    ("error", "Fehler"),
                    ("superseded", "ersetzt"),
                    ("awaiting_confirmation", "wartet auf Bestätigung"),
                ],
                default="complete",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="toolcall",
            name="arguments",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=multigpt.core.fields.UnicodeJSONEncoder,
                verbose_name="Argumente",
            ),
        ),
        migrations.AlterField(
            model_name="toolcall",
            name="result",
            field=models.JSONField(
                blank=True,
                encoder=multigpt.core.fields.UnicodeJSONEncoder,
                null=True,
                verbose_name="Ergebnis",
            ),
        ),
    ]
