# Generated by Django 5.2.18 on 2026-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_tool_loop"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="last_error",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Ursache, falls die letzte Prüfung fehlschlug (ohne Key); sonst leer.",
                verbose_name="Fehlerursache",
            ),
        ),
    ]
