# Generated by Django 5.2.18 on 2026-10-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_provider_last_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="current_leaf",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.message",
                verbose_name="angezeigte Version",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="chat.message",
                verbose_name="Vorgänger",
            ),
        ),
    ]
