# Generated by Django 5.2.18 on 2026-10-09 18:43

import django.core.validators
from django.db import migrations, models

import multigpt.chat.models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_message_branches_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Erst einschalten, wenn „SearXNG testen“ erfolgreich war.",
                        verbose_name="Websuche aktiv",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("searxng", "SearXNG")],
                        default="searxng",
                        max_length=20,
                        verbose_name="Such-Backend",
                    ),
                ),
                (
                    "searxng_url",
                    models.CharField(
                        blank=True,
                        help_text="Basisadresse der SearXNG-Instanz im Intranet, z. B. http://searx.intern:8888. SearXNG muss das JSON-Format erlauben (settings.yml: search.formats: [html, json]).",
                        max_length=500,
                        validators=[multigpt.chat.models.validate_service_url],
                        verbose_name="SearXNG-URL",
                    ),
                ),
                (
                    "max_results",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="So viele Treffer gehen als nummerierte Quellen an das Modell.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Trefferzahl",
                    ),
                ),
                (
                    "fetch_pages",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Von so vielen der besten Treffer wird der Seitentext abgerufen; von den übrigen nur der Kurztext der Suche. 0 = nur Kurztexte.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Seiten abrufen",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Höchstdauer für die Suche und je abgerufener Seite.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Zeitlimit (s)",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="de",
                        help_text="Sprachcode für SearXNG, z. B. de, en, de-DE oder all.",
                        max_length=20,
                        verbose_name="Sprache",
                    ),
                ),
                (
                    "safesearch",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "aus"), (1, "mittel"), (2, "streng")],
                        default=1,
                        help_text="SafeSearch der Suchmaschinen (soweit sie es unterstützen).",
                        verbose_name="Jugendschutzfilter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucheinstellungen",
                "verbose_name_plural": "Sucheinstellungen",
            },
        ),
    ]
