# Generated by Django 5.2.18 on 2026-10-09 18:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_search_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceref",
            name="page",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Seite"),
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Reihenfolge im Dokument, ab 0.", verbose_name="Position"
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "page",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Seitenzahl ab 1; leer bei Formaten ohne Seiten.",
                        null=True,
                        verbose_name="Seite",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=1536, verbose_name="Vektor"),
                ),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.SearchVector(
                            "text", config="german"
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                        verbose_name="Suchvektor",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="chat.document",
                        verbose_name="Dokument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abschnitt",
                "verbose_name_plural": "Abschnitte",
                "ordering": ["document", "position"],
            },
        ),
        migrations.AddField(
            model_name="sourceref",
            name="chunk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.chunk",
                verbose_name="Abschnitt",
            ),
        ),
        migrations.CreateModel(
            name="RagSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chunk_tokens",
                    models.PositiveIntegerField(
                        default=800,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(4000),
                        ],
                        verbose_name="Abschnittsgröße (Tokens)",
                    ),
                ),
                (
                    "overlap_tokens",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Überlappung (Tokens)",
                    ),
                ),
                (
                    "top_k",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="So viele Abschnitte gehen als Quellen an das Modell.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Treffer je Frage",
                    ),
                ),
                (
                    "hybrid",
                    models.BooleanField(
                        default=True,
                        help_text="Vektorsuche und Volltextsuche (deutsch) zusammenführen (Reciprocal Rank Fusion).",
                        verbose_name="Volltextsuche dazunehmen",
                    ),
                ),
                (
                    "embedding_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Genau ein Modell eines API-Anbieters (nicht LM Studio), z. B. text-embedding-3-small. Nach einem Wechsel „make reindex“ ausführen.",
                        limit_choices_to={"capability": "embedding"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.aimodel",
                        verbose_name="Embedding-Modell",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG-Einstellungen",
                "verbose_name_plural": "RAG-Einstellungen",
            },
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="chat_chunk_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="chat_chunk_search_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("document", "position"), name="chat_chunk_unique_document_position"
            ),
        ),
    ]
