# Generated by Django 5.2.18 on 2026-10-09 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_rag_chunks"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="last_error",
            field=models.TextField(blank=True, verbose_name="letzter Fehler"),
        ),
        migrations.AddField(
            model_name="job",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="in Arbeit seit"),
        ),
        migrations.AddField(
            model_name="job",
            name="run_after",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="frühestens ab"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status", "run_after"], name="chat_job_status_run_after"),
        ),
    ]
