# Generated by Django 5.2.18 on 2026-10-09 19:58
"""M7-09: Dokumentverarbeitung lokal.

- ``Chunk.embedding`` von vector(1536) auf vector(768) (nomic-embed-text-v1.5).
  Vorhandene Abschnitte passen nicht mehr und werden verworfen; alle Dokumente
  gehen auf „wartet“ und bekommen einen Indexierungsauftrag (der Worker bettet
  sie mit dem eingestellten Modell neu ein). Der HNSW-Index wird neu angelegt.
- ``RagSettings``: Präfixe für Abschnitte/Anfragen (nomic), OCR-Verfahren,
  OCR-Modell, Tesseract als Ersatz. Ist schon ein nomic- bzw. olmOCR-Modell
  vorhanden, werden Präfixe bzw. olmOCR vorbelegt.

Rückwärts gilt dasselbe in die andere Richtung (Abschnitte verworfen, neu
indexieren).
"""

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models

NOMIC_DOCUMENT_PREFIX = "search_document: "
NOMIC_QUERY_PREFIX = "search_query: "
INDEX_JOB = "index_document"


def drop_chunks_and_requeue(apps, schema_editor):
    """Abschnitte verwerfen (Dimension ändert sich), Dokumente neu einreihen."""
    Chunk = apps.get_model("chat", "Chunk")
    SourceRef = apps.get_model("chat", "SourceRef")
    Document = apps.get_model("chat", "Document")
    Job = apps.get_model("chat", "Job")
    # Fremdschlüssel prüfen sofort statt am Transaktionsende: Sonst scheitert das
    # folgende ALTER TABLE an „pending trigger events“.
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")
    SourceRef.objects.filter(chunk__isnull=False).update(chunk=None)
    Chunk.objects.all().delete()
    open_ids = set()
    for payload in Job.objects.filter(
        kind=INDEX_JOB, status__in=["pending", "running"]
    ).values_list("payload", flat=True):
        doc_id = (payload or {}).get("document_id")
        if isinstance(doc_id, int):
            open_ids.add(doc_id)
    Job.objects.filter(kind=INDEX_JOB, status="failed").delete()
    doc_ids = list(Document.objects.order_by("pk").values_list("pk", flat=True))
    Document.objects.update(status="pending", error_text="")
    Job.objects.bulk_create(
        [Job(kind=INDEX_JOB, payload={"document_id": pk}) for pk in doc_ids if pk not in open_ids]
    )


def preset_settings(apps, schema_editor):
    RagSettings = apps.get_model("chat", "RagSettings")
    AIModel = apps.get_model("chat", "AIModel")
    obj = RagSettings.objects.filter(pk=1).first()
    if obj is None:
        return
    fields = []
    model = AIModel.objects.filter(pk=obj.embedding_model_id).first()
    if model is not None and "nomic-embed" in model.model_id.lower():
        obj.document_prefix = NOMIC_DOCUMENT_PREFIX
        obj.query_prefix = NOMIC_QUERY_PREFIX
        fields += ["document_prefix", "query_prefix"]
    ocr = (
        AIModel.objects.filter(model_id__icontains="olmocr", provider__active=True)
        .order_by("pk")
        .first()
    )
    if ocr is not None:
        obj.ocr_backend = "olmocr"
        obj.ocr_model_id = ocr.pk
        fields += ["ocr_backend", "ocr_model"]
    if fields:
        obj.save(update_fields=fields)


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_job_retry"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragsettings",
            name="document_prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Wird jedem Abschnitt beim Einbetten vorangestellt, bei nomic-embed „search_document: “ (laut Modellkarte). Wird bei Auswahl eines nomic-Modells vorbelegt.",
                max_length=100,
                verbose_name="Präfix für Abschnitte",
            ),
        ),
        migrations.AddField(
            model_name="ragsettings",
            name="ocr_backend",
            field=models.CharField(
                choices=[
                    ("olmocr", "olmOCR (Vision-Modell, z. B. über LM Studio)"),
                    ("tesseract", "Tesseract (auf dem Server)"),
                ],
                default="tesseract",
                help_text="Texterkennung für gescannte PDF-Seiten ohne Textebene.",
                max_length=20,
                verbose_name="OCR-Verfahren",
            ),
        ),
        migrations.AddField(
            model_name="ragsettings",
            name="ocr_fallback_tesseract",
            field=models.BooleanField(
                default=True,
                help_text="Ist das OCR-Modell nicht erreichbar, liest Tesseract die Seite. Sonst wartet die Indexierung, bis der Anbieter wieder erreichbar ist.",
                verbose_name="Tesseract als Ersatz",
            ),
        ),
        migrations.AddField(
            model_name="ragsettings",
            name="ocr_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Vision-Modell für olmOCR, z. B. allenai/olmocr-2-7b in LM Studio. Wird auch genutzt, wenn es für den Chat deaktiviert ist.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.aimodel",
                verbose_name="OCR-Modell",
            ),
        ),
        migrations.AddField(
            model_name="ragsettings",
            name="query_prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Wird jeder Suchanfrage beim Einbetten vorangestellt, bei nomic-embed „search_query: “.",
                max_length=100,
                verbose_name="Präfix für Suchanfragen",
            ),
        ),
        migrations.RunPython(drop_chunks_and_requeue, drop_chunks_and_requeue),
        migrations.RemoveIndex(model_name="chunk", name="chat_chunk_embedding_hnsw"),
        migrations.AlterField(
            model_name="chunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=768, verbose_name="Vektor"),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="chat_chunk_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AlterField(
            model_name="ragsettings",
            name="embedding_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Genau ein Modell, z. B. text-embedding-nomic-embed-text-v1.5 über LM Studio (768 Dimensionen). Nach einem Wechsel „Alles neu indexieren“.",
                limit_choices_to={"capability": "embedding"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.aimodel",
                verbose_name="Embedding-Modell",
            ),
        ),
        migrations.RunPython(preset_settings, migrations.RunPython.noop),
    ]
