# Generated by Django 5.2.18 on 2026-10-09 19:59

import django.db.models.deletion
from django.db import migrations, models

import multigpt.chat.models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_local_rag"),
        ("rag", "0002_directorysource"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="rag.directorysource",
                verbose_name="Verzeichnisquelle",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source_mtime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="geändert (Quelle)"),
        ),
        migrations.AddField(
            model_name="document",
            name="source_path",
            field=models.CharField(blank=True, max_length=1000, verbose_name="Pfad in der Quelle"),
        ),
        migrations.AddField(
            model_name="document",
            name="source_sha256",
            field=models.CharField(blank=True, max_length=64, verbose_name="SHA-256 (Quelle)"),
        ),
        migrations.AddField(
            model_name="document",
            name="source_size",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Größe (Quelle)"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                upload_to=multigpt.chat.models.document_upload_to,
                verbose_name="Datei",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="kind",
            field=models.CharField(
                choices=[
                    ("index_document", "Dokument indexieren"),
                    ("scan_directory", "Verzeichnis einlesen"),
                ],
                max_length=50,
                verbose_name="Art",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source__isnull", False)),
                fields=("source", "source_path"),
                name="chat_document_unique_source_path",
            ),
        ),
    ]
