# Generated by Django 5.2.18 on 2026-10-10
"""Kontextkopf je Abschnitt: Dokumentname (und Ordnerpfad) im Index.

- ``Chunk.heading`` (neu): „Dokument: …“, bei Verzeichnisquellen „Pfad: …“,
  „Seite: …“. Wird beim Einbetten vor den Text gestellt.
- ``Chunk.search_vector``: Kopf (Gewicht A) und Text (Gewicht B). PostgreSQL
  kann den Ausdruck einer Generated-Spalte nicht ändern; Spalte und GIN-Index
  werden deshalb entfernt und neu angelegt (berechnet für alle Zeilen).
- Bestehende Abschnitte haben noch keinen Kopf, bleiben aber über ihren Text
  durchsuchbar. Für jedes indexierte Dokument wird ein Indexierungsauftrag
  eingereiht (sofern keiner offen ist); der Worker ersetzt die Abschnitte in
  einer Transaktion.

Rückwärts: Feld entfernen, alte Spalte ``to_tsvector('german', text)`` und
Index wiederherstellen. Die eingereihten Aufträge bleiben (schaden nicht).
"""

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models

INDEX_JOB = "index_document"


def requeue_indexed(apps, schema_editor):
    """Indexierte Dokumente neu einreihen (historische Modelle, wie 0014)."""
    Document = apps.get_model("chat", "Document")
    Job = apps.get_model("chat", "Job")
    open_ids = set()
    for payload in Job.objects.filter(
        kind=INDEX_JOB, status__in=["pending", "running"]
    ).values_list("payload", flat=True):
        doc_id = (payload or {}).get("document_id")
        if isinstance(doc_id, int):
            open_ids.add(doc_id)
    doc_ids = list(
        Document.objects.filter(status="indexed").order_by("pk").values_list("pk", flat=True)
    )
    Document.objects.filter(pk__in=doc_ids).update(status="pending", error_text="")
    Job.objects.bulk_create(
        [Job(kind=INDEX_JOB, payload={"document_id": pk}) for pk in doc_ids if pk not in open_ids]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_document_source"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="chunk", name="chat_chunk_search_gin"),
        migrations.RemoveField(model_name="chunk", name="search_vector"),
        migrations.AddField(
            model_name="chunk",
            name="heading",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Dokumentname, Pfad und Seite; wird mit eingebettet und durchsucht.",
                verbose_name="Kontextkopf",
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "heading", config="german", weight="A"
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "text", config="german", weight="B"
                    ),
                    django.contrib.postgres.search.SearchConfig("german"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
                verbose_name="Suchvektor",
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="chat_chunk_search_gin"
            ),
        ),
        migrations.RunPython(requeue_indexed, migrations.RunPython.noop),
    ]
