# Generated by Django 5.2.18 on 2026-10-09 22:43

"""Abbrechen von Aufträgen und Läufe der Indexierung.

- ``Job.cancel_requested`` (neu): Abbruch eines laufenden Auftrags angefordert;
  der Worker beendet ihn an der nächsten Prüfstelle.
- ``IndexRun`` (neu): Lauf (Verzeichnis einlesen, Alles/Sammlung neu indexieren,
  Upload) mit Status, Zählern und Zeiten; ``Job.run`` verweist darauf.

Nur neue Spalten/Tabellen mit Standardwerten; bestehende Aufträge haben keinen
Lauf. Rückwärts: Tabelle und Spalten entfernen.
"""

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0016_chunk_heading"),
        ("rag", "0002_directorysource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cancel_requested",
            field=models.BooleanField(default=False, verbose_name="Abbruch angefordert"),
        ),
        migrations.CreateModel(
            name="IndexRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("directory_scan", "Verzeichnis einlesen"),
                            ("reindex_all", "Alles neu indexieren"),
                            ("reindex_collection", "Sammlung neu indexieren"),
                            ("upload", "Hochladen"),
                        ],
                        max_length=30,
                        verbose_name="Art",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "läuft"),
                            ("cancelling", "wird abgebrochen"),
                            ("cancelled", "abgebrochen"),
                            ("finished", "beendet"),
                            ("failed", "fehlgeschlagen"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "files_found",
                    models.PositiveIntegerField(default=0, verbose_name="Dateien gefunden"),
                ),
                (
                    "files_checked",
                    models.PositiveIntegerField(default=0, verbose_name="Dateien geprüft"),
                ),
                ("files_new", models.PositiveIntegerField(default=0, verbose_name="Dateien neu")),
                (
                    "files_changed",
                    models.PositiveIntegerField(default=0, verbose_name="Dateien geändert"),
                ),
                (
                    "files_deleted",
                    models.PositiveIntegerField(default=0, verbose_name="Dateien entfernt"),
                ),
                (
                    "files_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="Dateien übersprungen"),
                ),
                (
                    "docs_queued",
                    models.PositiveIntegerField(default=0, verbose_name="Dokumente eingereiht"),
                ),
                (
                    "docs_done",
                    models.PositiveIntegerField(default=0, verbose_name="Dokumente fertig"),
                ),
                (
                    "docs_failed",
                    models.PositiveIntegerField(default=0, verbose_name="Dokumente mit Fehler"),
                ),
                (
                    "docs_cancelled",
                    models.PositiveIntegerField(default=0, verbose_name="Dokumente abgebrochen"),
                ),
                ("error_text", models.TextField(blank=True, verbose_name="Fehler")),
                (
                    "started",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="gestartet"
                    ),
                ),
                ("finished", models.DateTimeField(blank=True, null=True, verbose_name="beendet")),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="index_runs",
                        to="chat.collection",
                        verbose_name="Sammlung",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="rag.directorysource",
                        verbose_name="Verzeichnisquelle",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gestartet von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lauf",
                "verbose_name_plural": "Läufe",
                "ordering": ["-started", "-id"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="chat.indexrun",
                verbose_name="Lauf",
            ),
        ),
        migrations.AddIndex(
            model_name="indexrun",
            index=models.Index(fields=["status"], name="chat_indexrun_status"),
        ),
    ]
