# Generated by Django 5.2.18 on 2026-10-09 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import multigpt.chat.models
from multigpt.chat.capabilities import guess_vision


def fill_vision_and_owner(apps, schema_editor):
    """Bild-Eingabe nach ID-Muster vorbelegen (Chat-Modelle); Besitzer
    vorhandener Anhänge = Besitzer des Chats."""
    AIModel = apps.get_model("chat", "AIModel")
    vision = [
        pk
        for pk, model_id in AIModel.objects.filter(capability="chat").values_list("pk", "model_id")
        if guess_vision(model_id)
    ]
    AIModel.objects.filter(pk__in=vision).update(supports_vision=True)
    Attachment = apps.get_model("chat", "Attachment")
    for att in Attachment.objects.filter(owner__isnull=True, message__isnull=False).select_related(
        "message__conversation"
    ):
        att.owner_id = att.message.conversation.user_id
        att.save(update_fields=["owner"])


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0017_index_runs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="supports_vision",
            field=models.BooleanField(
                default=False,
                help_text="Bilder im Chat dürfen an dieses Modell gehen (Bild-Eingabe).",
                verbose_name="versteht Bilder",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.conversation",
                verbose_name="Chat (beim Hochladen)",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                help_text="Text von Dokumenten (gekürzt).",
                verbose_name="Extrahierter Text",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Höhe"),
        ),
        migrations.AddField(
            model_name="attachment",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100, verbose_name="Inhaltstyp"),
        ),
        migrations.AddField(
            model_name="attachment",
            name="original_name",
            field=models.CharField(
                blank=True,
                help_text="Nur zur Anzeige, bereinigt.",
                max_length=255,
                verbose_name="Dateiname",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Wer die Datei hochgeladen hat (bei erzeugten Dateien leer).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Besitzer",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="size",
            field=models.PositiveBigIntegerField(default=0, verbose_name="Größe (Bytes)"),
        ),
        migrations.AddField(
            model_name="attachment",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                max_length=255,
                upload_to=multigpt.chat.models.attachment_thumbnail_upload_to,
                verbose_name="Vorschaubild",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Breite"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="chat.message",
                verbose_name="Nachricht",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                condition=models.Q(("message__isnull", True)),
                fields=["created"],
                name="chat_attachment_draft_created",
            ),
        ),
        migrations.RunPython(fill_vision_and_owner, migrations.RunPython.noop),
    ]
