# Generated by Django 5.2.18 on 2026-10-10 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_citation_prefs"),
        ("chat", "0020_figures"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ansicht eines geteilten Chats",
                "verbose_name_plural": "Ansichten geteilter Chats",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verfasser",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="can_delete",
            field=models.BooleanField(default=False, verbose_name="Löschen"),
        ),
        migrations.AddField(
            model_name="share",
            name="can_update",
            field=models.BooleanField(default=False, verbose_name="Bearbeiten"),
        ),
        migrations.AddField(
            model_name="share",
            name="left_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aus der Liste entfernt von",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_shares",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Konto",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="accounts.usergroup",
                verbose_name="Gruppe",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["author", "created"], name="chat_msg_author_created"),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("group__isnull", False), ("user__isnull", True)),
                    models.Q(("group__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="chat_share_exactly_one_recipient",
                violation_error_message="Freigabe gilt genau einer Gruppe oder einem Konto.",
            ),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("collection__isnull", True), ("group__isnull", False), _connector="OR"
                ),
                name="chat_share_collection_group_only",
                violation_error_message="Sammlungen werden nur an Gruppen geteilt.",
            ),
        ),
        migrations.AddConstraint(
            model_name="share",
            constraint=models.UniqueConstraint(
                condition=models.Q(("conversation__isnull", False), ("user__isnull", False)),
                fields=("conversation", "user"),
                name="chat_share_unique_conversation_user",
            ),
        ),
        migrations.AddField(
            model_name="conversationview",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="chat.conversation",
                verbose_name="Chat",
            ),
        ),
        migrations.AddField(
            model_name="conversationview",
            name="current_leaf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.message",
                verbose_name="angezeigte Version",
            ),
        ),
        migrations.AddField(
            model_name="conversationview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Konto",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationview",
            constraint=models.UniqueConstraint(
                fields=("conversation", "user"), name="chat_conversationview_unique"
            ),
        ),
    ]
