# Generated by Django 5.2.18 on 2026-10-10 00:39
#
# Fähigkeiten-Matrix und MCP-Freigabe je Modell. Bestehende Modelle bekommen
# mcp_access „all“ (keine Verhaltensänderung), neue danach „none“ als
# Vorgabe; Hauptart MUSIC (M11) und klarere Bezeichnungen. Keine Datenmigration.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0021_chat_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="mcp_access",
            field=models.CharField(
                choices=[("none", "kein"), ("all", "alle"), ("selected", "ausgewählte")],
                default="all",
                help_text="Welche MCP-Server das Modell nutzen darf (zusätzlich zu den Rechten der Rolle). „kein“ trennt nicht vertrauenswürdige Modelle von Werkzeugen, die etwas verändern können.",
                max_length=10,
                verbose_name="MCP",
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="mcp_access",
            field=models.CharField(
                choices=[("none", "kein"), ("all", "alle"), ("selected", "ausgewählte")],
                default="none",
                help_text="Welche MCP-Server das Modell nutzen darf (zusätzlich zu den Rechten der Rolle). „kein“ trennt nicht vertrauenswürdige Modelle von Werkzeugen, die etwas verändern können.",
                max_length=10,
                verbose_name="MCP",
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="mcp_servers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Nur bei MCP „ausgewählte“ wirksam.",
                related_name="allowed_models",
                to="chat.mcpserver",
                verbose_name="erlaubte MCP-Server",
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="can_edit_images",
            field=models.BooleanField(
                default=False,
                help_text="Kann vorhandene Bilder bearbeiten bzw. Varianten erzeugen (M9-02).",
                verbose_name="Bilder bearbeiten",
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="capability",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("image", "Bilderzeugung"),
                    ("embedding", "Embedding"),
                    ("stt", "Spracherkennung"),
                    ("tts", "Sprachausgabe"),
                    ("music", "Musik"),
                ],
                default="chat",
                help_text="Hauptart. Nur Chat-Modelle erscheinen in der Chat-Auswahl.",
                max_length=20,
                verbose_name="Fähigkeit",
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="supports_tools",
            field=models.BooleanField(
                default=False,
                help_text="Kann Werkzeuge aufrufen (Function Calling): Websuche als Werkzeug, Dokumentsuche, MCP-Server.",
                verbose_name="Werkzeuge",
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="supports_vision",
            field=models.BooleanField(
                default=False,
                help_text="Bilder im Chat dürfen an dieses Modell gehen (Bild-Eingabe).",
                verbose_name="Bilder verstehen",
            ),
        ),
    ]
