# Generated by Django 5.2.18 on 2026-10-10 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0022_model_capabilities_mcp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("instructions", models.TextField(blank=True, verbose_name="Anweisungen")),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "ohne"),
                            ("blue", "Blau"),
                            ("green", "Grün"),
                            ("yellow", "Gelb"),
                            ("orange", "Orange"),
                            ("red", "Rot"),
                            ("purple", "Lila"),
                            ("gray", "Grau"),
                        ],
                        max_length=10,
                        verbose_name="Farbe",
                    ),
                ),
                ("pinned", models.BooleanField(default=False, verbose_name="angeheftet")),
                ("archived", models.BooleanField(default=False, verbose_name="archiviert")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="erstellt")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="geändert")),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="chat.collection",
                        verbose_name="Sammlungen",
                    ),
                ),
                (
                    "default_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.aimodel",
                        verbose_name="Standardmodell",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Besitzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekte",
                "ordering": ["-pinned", "name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="chat.project",
                verbose_name="Projekt",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner", "archived"], name="chat_project_owner_archived"),
        ),
    ]
