# Generated by Django 5.2.18 on 2026-10-10 00:49

import django.core.validators
from django.db import migrations, models

# Kopie von models.DEFAULT_BASE_INSTRUCTIONS zum Zeitpunkt dieser Migration –
# bewusst nicht importiert, damit spätere Textänderungen sie nicht verändern.
BASE_INSTRUCTIONS = (
    "Erfinde keine URLs, Zahlen, Namen, Ereignisse oder Zitate. Nenne Links nur, wenn sie "
    "aus Quellmaterial oder Werkzeugergebnissen stammen. Wenn du etwas nicht überprüfen "
    "kannst, sag das ausdrücklich und biete an, mit der Websuche nachzusehen."
)


def seed_base_instructions(apps, schema_editor):
    """Datensatz anlegen, falls er fehlt; Grundregeln nur setzen, wenn leer
    (idempotent, überschreibt nie einen Text des Verwalters)."""
    ChatSettings = apps.get_model("chat", "ChatSettings")
    obj, _ = ChatSettings.objects.get_or_create(
        pk=1, defaults={"base_instructions": BASE_INSTRUCTIONS}
    )
    if not (obj.base_instructions or "").strip():
        obj.base_instructions = BASE_INSTRUCTIONS
        obj.save(update_fields=["base_instructions"])


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0023_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "base_instructions",
                    models.TextField(
                        blank=True,
                        default="Erfinde keine URLs, Zahlen, Namen, Ereignisse oder Zitate. Nenne Links nur, wenn sie aus Quellmaterial oder Werkzeugergebnissen stammen. Wenn du etwas nicht überprüfen kannst, sag das ausdrücklich und biete an, mit der Websuche nachzusehen.",
                        help_text="Gehen bei jedem Chat an jedes Modell, als erster Teil des System-Prompts – vor den Hinweisen von MultiGPT, den Projekt-Anweisungen und dem System-Prompt des Chats. Leer = keine Grundregeln.",
                        verbose_name="Grundregeln für alle Modelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat-Einstellungen",
                "verbose_name_plural": "Chat-Einstellungen",
            },
        ),
        migrations.AddField(
            model_name="searchsettings",
            name="blocked_domains",
            field=models.TextField(
                blank=True,
                help_text="Eine Domain je Zeile, Subdomains eingeschlossen (example.com sperrt auch www.example.com). Gilt für fetch_url, crawl_site und den Abruf von Suchtreffern.",
                verbose_name="Gesperrte Domains",
            ),
        ),
        migrations.AddField(
            model_name="searchsettings",
            name="crawl_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Modelle mit Werkzeugen dürfen Links einer Website folgen (robots.txt wird beachtet).",
                verbose_name="Websites durchsuchen (crawl_site)",
            ),
        ),
        migrations.AddField(
            model_name="searchsettings",
            name="crawl_max_pages",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Obergrenze für crawl_site (höchstens 20, Linktiefe höchstens 2).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="Seiten je Durchsuchung",
            ),
        ),
        migrations.AddField(
            model_name="searchsettings",
            name="crawl_time_seconds",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Gesamtdauer einer Durchsuchung; danach zählen die bis dahin gelesenen Seiten.",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Zeitlimit Durchsuchung (s)",
            ),
        ),
        migrations.AddField(
            model_name="searchsettings",
            name="fetch_url_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Modelle mit Werkzeugen dürfen einzelne Webseiten lesen; im festen Ablauf werden URLs aus der Frage mit abgerufen.",
                verbose_name="Seiten abrufen (fetch_url)",
            ),
        ),
        migrations.RunPython(seed_base_instructions, migrations.RunPython.noop),
    ]
