# Generated by Django 5.2.18 on 2026-10-10 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0026_remove_aimodel_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsettings",
            name="default_image_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Für das Werkzeug „Bild erzeugen“ und den Modus „Bild“. Leer bzw. nicht nutzbar (Rolle, Budget, offline) = das erste freigegebene Bildmodell.",
                limit_choices_to={"capability": "image"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chat.aimodel",
                verbose_name="Standard-Bildmodell",
            ),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="image_tool_confirm",
            field=models.BooleanField(
                default=False,
                help_text="Chatmodelle fragen vor jedem Bild über das Werkzeug nach (Bilder kosten Geld). Aus: ohne Rückfrage, das Budget wird trotzdem vor jedem Bild geprüft.",
                verbose_name="Rückfrage vor Bilderzeugung",
            ),
        ),
    ]
