# Generated by Django 5.2.18 on 2026-10-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0027_image_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpserver",
            name="last_checked",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="zuletzt geprüft"
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="last_error",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Ursache, falls die letzte Prüfung fehlschlug (ohne Zugangsdaten); sonst leer.",
                verbose_name="Fehlerursache",
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="last_online",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="zuletzt online"
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="online",
            field=models.BooleanField(default=False, editable=False, verbose_name="online"),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="reported_tools",
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text="Werkzeuge der letzten erfolgreichen Prüfung: Name, gekürzte Beschreibung, Parameternamen und Hinweise (annotations) des Servers.",
                verbose_name="gemeldete Werkzeuge",
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="tools_checked",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Zeitpunkt, zu dem ein Verwalter die Einstufung der Werkzeuge zuletzt geändert hat.",
                null=True,
                verbose_name="zuletzt eingestuft",
            ),
        ),
    ]
