# Generated by Django 5.2.18 on 2026-10-10 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0028_mcp_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsettings",
            name="python_confirm",
            field=models.BooleanField(
                default=False,
                help_text="Chatmodelle fragen vor jeder Ausführung nach. Aus: ohne Rückfrage – der Code läuft ohnehin abgeschottet (kein Netz, keine Server-Dateien).",
                verbose_name="Rückfrage vor Berechnungen",
            ),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="python_cpu_seconds",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="CPU-Zeit (s)",
            ),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="python_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Werkzeug run_python für Modelle mit Werkzeugen (Recht „Berechnungen ausführen“). Wird nur angeboten, wenn die Sandbox (bubblewrap) funktioniert.",
                verbose_name="Berechnungen aktiv",
            ),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="python_file_mb",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Höchstgröße je Datei im Arbeitsordner.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Dateigröße (MB)",
            ),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="python_memory_mb",
            field=models.PositiveIntegerField(
                default=512,
                validators=[
                    django.core.validators.MinValueValidator(128),
                    django.core.validators.MaxValueValidator(4096),
                ],
                verbose_name="Speicher je Prozess (MB)",
            ),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="python_output_kb",
            field=models.PositiveSmallIntegerField(
                default=64,
                help_text="So viel Text (stdout/stderr) geht an das Modell; der Rest wird gekürzt.",
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(1024),
                ],
                verbose_name="Ausgabe (KB)",
            ),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="python_processes",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Einschließlich Python selbst und dem Start-Prozess der Sandbox.",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(64),
                ],
                verbose_name="Prozesse und Threads",
            ),
        ),
        migrations.AddField(
            model_name="chatsettings",
            name="python_wall_seconds",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Danach wird der Lauf abgebrochen (Wanduhr, auch beim Warten).",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Laufzeit gesamt (s)",
            ),
        ),
    ]
