# Generated by Django 5.2.18 on 2026-10-10 05:18

from django.db import migrations, models


def olmocr_to_ocr(apps, schema_editor):
    """olmOCR ist ein reines OCR-Modell: aus der Chat-Auswahl nehmen.

    Nur Modelle, die noch auf „chat“ stehen; eine bewusst andere Hauptart bleibt.
    Mehrfach ausführbar (danach steht keines mehr auf „chat“).
    """
    AIModel = apps.get_model("chat", "AIModel")
    AIModel.objects.filter(model_id__icontains="olmocr", capability="chat").update(capability="ocr")


def ocr_to_chat(apps, schema_editor):
    """Rückweg: Vor 0030 gab es „ocr“ nicht, OCR-Modelle standen auf „chat“."""
    AIModel = apps.get_model("chat", "AIModel")
    AIModel.objects.filter(capability="ocr").update(capability="chat")


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0029_python_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="capability",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("image", "Bilderzeugung"),
                    ("embedding", "Embedding"),
                    ("stt", "Spracherkennung"),
                    ("tts", "Sprachausgabe"),
                    ("music", "Musik"),
                    ("ocr", "Texterkennung (OCR)"),
                ],
                default="chat",
                help_text="Hauptart. Nur Chat-Modelle erscheinen in der Chat-Auswahl.",
                max_length=20,
                verbose_name="Fähigkeit",
            ),
        ),
        migrations.RunPython(olmocr_to_ocr, ocr_to_chat),
    ]
