# Generated by Django 5.2.18 on 2026-10-10 06:26

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0030_aimodel_capability_ocr"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsettings",
            name="default_temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.3"),
                help_text="0 bis 2; niedrig = sachlich und wiederholbar, hoch = abwechslungsreicher, aber eher erfunden. 0,3 ist sachlich. Gilt für Chats ohne eigene Wahl unter „Kreativität“ und ohne Projektvorgabe. Leer = Standard des Anbieters (oft 0,7–1,0). Modelle, die keine Temperatur annehmen (z. B. OpenAI o-Serie und GPT-5, neuere Claude-Modelle), bekommen keine.",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("2")),
                ],
                verbose_name="Standard-Kreativität (Temperatur)",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("2")),
                ],
                verbose_name="Kreativität (Temperatur)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("2")),
                ],
                verbose_name="Kreativität",
            ),
        ),
        migrations.AlterField(
            model_name="chatsettings",
            name="base_instructions",
            field=models.TextField(
                blank=True,
                default="Erfinde keine URLs, Zahlen, Namen, Ereignisse oder Zitate. Nenne Links nur, wenn sie aus Quellmaterial oder Werkzeugergebnissen stammen. Wenn du etwas nicht überprüfen kannst, sag das ausdrücklich und biete an, mit der Websuche nachzusehen.",
                help_text="Gehen bei jedem Chat an jedes Modell, als erster Teil des System-Prompts – vor den Hinweisen von MultiGPT, den Projekt-Anweisungen und dem System-Prompt des Chats. Nutzer sehen sie im Chat unter „System-Prompt“ (nur lesend). Leer = keine Grundregeln. Bei zu ausschweifenden Antworten hilft z. B. der Zusatz „Antworte sachlich und knapp. Wenn du etwas vermutest, kennzeichne es als Vermutung.“",
                verbose_name="Grundregeln für alle Modelle",
            ),
        ),
    ]
