# Generated by Django 5.2.18 on 2026-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0031_creativity"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsettings",
            name="default_reasoning_effort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("off", "Aus/minimal"),
                    ("low", "Niedrig"),
                    ("medium", "Mittel"),
                    ("high", "Hoch"),
                    ("xhigh", "Sehr hoch"),
                    ("max", "Maximal"),
                ],
                default="",
                help_text="Wie gründlich Modelle mit Reasoning vor der Antwort nachdenken. Höher = gründlicher, aber langsamer und teurer (Denk-Tokens werden als Ausgabe berechnet). Gilt für Chats ohne eigene Wahl unter „Denktiefe“ und ohne Projektvorgabe. Leer = Standard des Anbieters. Modelle ohne Reasoning bekommen nichts; nicht unterstützte Stufen werden auf die nächste passende abgebildet.",
                max_length=10,
                verbose_name="Standard-Denktiefe",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="reasoning_effort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("off", "Aus/minimal"),
                    ("low", "Niedrig"),
                    ("medium", "Mittel"),
                    ("high", "Hoch"),
                    ("xhigh", "Sehr hoch"),
                    ("max", "Maximal"),
                ],
                default="",
                max_length=10,
                verbose_name="Denktiefe",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reasoning_effort",
            field=models.CharField(
                blank=True,
                choices=[
                    ("off", "Aus/minimal"),
                    ("low", "Niedrig"),
                    ("medium", "Mittel"),
                    ("high", "Hoch"),
                    ("xhigh", "Sehr hoch"),
                    ("max", "Maximal"),
                ],
                default="",
                max_length=10,
                verbose_name="Denktiefe",
            ),
        ),
    ]
