# Generated by Django 5.2.18 on 2026-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0032_reasoning_effort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("directory_scan", "Verzeichnis einlesen"),
                    ("reindex_all", "Alles neu indexieren"),
                    ("reindex_collection", "Sammlung neu indexieren"),
                    ("reindex_documents", "Dokumente neu indexieren"),
                    ("upload", "Hochladen"),
                ],
                max_length=30,
                verbose_name="Art",
            ),
        ),
    ]
