# Generated by Django 5.2.18 on 2026-10-09 14:58

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                (
                    "key",
                    models.SlugField(
                        help_text="Stabiler technischer Schlüssel, z. B. admin, adult, teen, guest.",
                        unique=True,
                        verbose_name="Schlüssel",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Darf Anbieter, Modelle, Konten, Rollen, Gruppen und Budgets verwalten und den Verbrauch aller Mitglieder sehen.",
                        verbose_name="Verwaltungsrechte",
                    ),
                ),
                (
                    "all_models",
                    models.BooleanField(
                        default=False,
                        help_text="Wenn gesetzt, sind alle aktiven Modelle erlaubt und die Liste „Erlaubte Modelle“ wird ignoriert. Sonst gilt nur die Liste (leer = keines).",
                        verbose_name="Alle aktiven Modelle",
                    ),
                ),
                ("can_web_search", models.BooleanField(default=False, verbose_name="Websuche")),
                (
                    "can_images",
                    models.BooleanField(
                        default=False, verbose_name="Bilder erzeugen und bearbeiten"
                    ),
                ),
                (
                    "can_voice",
                    models.BooleanField(
                        default=False, verbose_name="Sprache (Aufnahme und Vorlesen)"
                    ),
                ),
                (
                    "can_upload_documents",
                    models.BooleanField(default=False, verbose_name="Dokumente hochladen"),
                ),
                (
                    "can_share",
                    models.BooleanField(default=False, verbose_name="Mit Gruppen teilen"),
                ),
                (
                    "all_mcp_servers",
                    models.BooleanField(
                        default=False,
                        help_text="Wenn gesetzt, sind alle aktiven MCP-Server erlaubt. Sonst gilt nur die Liste (leer = keiner).",
                        verbose_name="Alle aktiven MCP-Server",
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leer = unbegrenzt.",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Monatsbudget (EUR)",
                    ),
                ),
                (
                    "fixed_system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Wird jedem Chat vorangestellt; für das Mitglied weder sichtbar änderbar noch abschaltbar.",
                        verbose_name="Fester System-Prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rolle",
                "verbose_name_plural": "Rollen",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="allow_supervision",
            field=models.BooleanField(
                default=False,
                help_text="Verwalter dürfen die Chats dieses Kontos einsehen. Das Mitglied sieht in der Oberfläche, dass die Option aktiv ist.",
                verbose_name="Einsicht in Chats erlaubt",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="auto_read_aloud",
            field=models.BooleanField(default=False, verbose_name="Antworten automatisch vorlesen"),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Anzeigename"),
        ),
        migrations.AddField(
            model_name="user",
            name="monthly_budget_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Überschreibt das Budget der Rolle. Leer = Budget der Rolle.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Eigenes Monatsbudget (EUR)",
            ),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Jedes neue Konto wird automatisch Mitglied.",
                verbose_name="Standardgruppe",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.role",
                verbose_name="Rolle",
            ),
        ),
    ]
