# Generated by Django 5.2.18 on 2026-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_initial_roles_and_family"),
        ("chat", "0002_provider_aimodel_mcpserver"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="allowed_mcp_servers",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                to="chat.mcpserver",
                verbose_name="Erlaubte MCP-Server",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="allowed_models",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="chat.aimodel", verbose_name="Erlaubte Modelle"
            ),
        ),
    ]
