# Generated by Django 5.2.18 on 2026-10-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_citation_prefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mark_unverified_links",
            field=models.BooleanField(
                default=True,
                help_text="Links in Antworten, die aus keiner Quelle und keinem Werkzeugergebnis stammen, bekommen ein Warnsymbol.",
                verbose_name="Ungeprüfte Links markieren",
            ),
        ),
    ]
