# Generated by Django 5.2.18 on 2026-10-10 01:01

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_mark_unverified_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="monthly_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Über alle monetären Abrechnungskonten. Leer = unbegrenzt. Budgets je Konto: Kosten und Abrechnung › Abrechnungskonten.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Monatsbudget gesamt (EUR)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="monthly_budget_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Überschreibt das Budget der Rolle. Leer = Budget der Rolle.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Eigenes Monatsbudget gesamt (EUR)",
            ),
        ),
    ]
