# Generated by Django 5.2.18 on 2026-10-10 01:55

"""Recht „Berechnungen ausführen“ (M4a-10, Werkzeug run_python).

Neue Rollen: aus (fail closed). Startrollen Verwalter, Erwachsener und
Jugendlicher: an – der Code läuft in der Sandbox (kein Netz, keine
Server-Dateien), Rechnen hilft gerade bei Hausaufgaben. Gast: aus.
"""

from django.db import migrations, models

ENABLED_KEYS = ("admin", "adult", "teen")


def enable(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.filter(key__in=ENABLED_KEYS).update(can_compute=True)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_total_budget_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_compute",
            field=models.BooleanField(
                default=False,
                help_text="Modelle dürfen Python-Code für Rechnungen in einer abgeschotteten "
                "Umgebung ausführen (numpy, sympy, Diagramme).",
                verbose_name="Berechnungen ausführen",
            ),
        ),
        migrations.RunPython(enable, migrations.RunPython.noop),
    ]
