# Generated by Django 5.2.18 on 2026-10-10 01:01

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0006_mark_unverified_links"),
        ("chat", "0024_web_fetch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Gilt ab diesem Tag (Europe/Berlin).",
                        unique=True,
                        verbose_name="Datum",
                    ),
                ),
                (
                    "usd_eur",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="z. B. 0,86 (EZB veröffentlicht EUR->USD, z. B. 1,16; Kehrwert eintragen).",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.000001"))],
                        verbose_name="1 USD in EUR",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "von Hand"), ("ecb", "EZB-Referenzkurs")],
                        default="manual",
                        max_length=10,
                        verbose_name="Quelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wechselkurs",
                "verbose_name_plural": "Wechselkurse",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("monetary", "monetär (Preise je Token)"),
                            ("tokens", "nur Tokens (z. B. lokal)"),
                            ("flat", "Pauschale/Abo (nur gezählt)"),
                        ],
                        default="monetary",
                        max_length=10,
                        verbose_name="Art",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("EUR", "Euro (EUR)"), ("USD", "US-Dollar (USD)")],
                        help_text="Nur bei monetären Konten; in dieser Währung stehen die Preise. Lässt sich nicht mehr ändern, sobald Preise oder Buchungen existieren.",
                        max_length=3,
                        verbose_name="Währung",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="z. B. Vertragsnummer, Abo-Preis.",
                        verbose_name="Notiz",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inaktiv: Modelle der zugeordneten Anbieter sind gesperrt (z. B. Abo gekündigt).",
                        verbose_name="aktiv",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="angelegt")),
            ],
            options={
                "verbose_name": "Abrechnungskonto",
                "verbose_name_plural": "Abrechnungskonten",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "monetary"), models.Q(("currency", ""), _negated=True)
                            ),
                            models.Q(
                                models.Q(("kind", "monetary"), _negated=True), ("currency", "")
                            ),
                            _connector="OR",
                        ),
                        name="billing_account_currency_by_kind",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="gültig ab"
                    ),
                ),
                (
                    "input",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="je 1 Mio. Tokens",
                        max_digits=12,
                        null=True,
                        verbose_name="Eingabe",
                    ),
                ),
                (
                    "cached_input",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="je 1 Mio. Tokens in der Währung des Kontos; leer = wie Eingabe",
                        max_digits=12,
                        null=True,
                        verbose_name="Eingabe aus Cache",
                    ),
                ),
                (
                    "cache_write",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="je 1 Mio. Tokens in der Währung des Kontos; leer = wie Eingabe (Anthropic: 5-Minuten-Cache)",
                        max_digits=12,
                        null=True,
                        verbose_name="Cache schreiben (5 Min.)",
                    ),
                ),
                (
                    "cache_write_1h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="je 1 Mio. Tokens; leer = wie „Cache schreiben (5 Min.)“",
                        max_digits=12,
                        null=True,
                        verbose_name="Cache schreiben (1 Std.)",
                    ),
                ),
                (
                    "output",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="je 1 Mio. Tokens, einschließlich Reasoning-/Nachdenk-Tokens",
                        max_digits=12,
                        null=True,
                        verbose_name="Ausgabe",
                    ),
                ),
                (
                    "long_context_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Liegt die Eingabe einer Anfrage darüber, gelten für die ganze Anfrage die Langkontext-Preise (z. B. 200000). Leer = kein Langkontext-Tarif.",
                        null=True,
                        verbose_name="Langkontext ab (Tokens)",
                    ),
                ),
                (
                    "long_input",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="Langkontext: Eingabe",
                    ),
                ),
                (
                    "long_cached_input",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="Langkontext: Eingabe aus Cache",
                    ),
                ),
                (
                    "long_cache_write",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="Langkontext: Cache schreiben (5 Min.)",
                    ),
                ),
                (
                    "long_cache_write_1h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="Langkontext: Cache schreiben (1 Std.)",
                    ),
                ),
                (
                    "long_output",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="Langkontext: Ausgabe",
                    ),
                ),
                (
                    "unit_prices",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON, z. B. {"web_search": 0.01, "image:high": 0.17}. Schlüssel: web_search, web_fetch, image, audio_minute, tts_characters, request',
                        verbose_name="Gebühren je Einheit",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="z. B. Preisseite und Datum.",
                        max_length=300,
                        verbose_name="Quelle/Notiz",
                    ),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="chat.aimodel",
                        verbose_name="Modell",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modellpreis",
                "verbose_name_plural": "Modellpreise",
                "ordering": ["ai_model", "-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="UsageEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("answer", "Antwort"),
                            ("attachment", "Datei/Anhang"),
                            ("tool", "Werkzeuggebühr"),
                        ],
                        default="answer",
                        max_length=12,
                        verbose_name="Art",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Modellname"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Zeitpunkt"
                    ),
                ),
                ("tokens_in", models.PositiveBigIntegerField(default=0, verbose_name="Eingabe")),
                ("tokens_out", models.PositiveBigIntegerField(default=0, verbose_name="Ausgabe")),
                (
                    "cached_read",
                    models.PositiveBigIntegerField(default=0, verbose_name="davon Cache gelesen"),
                ),
                (
                    "cache_write",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="davon Cache geschrieben (5 Min.)"
                    ),
                ),
                (
                    "cache_write_1h",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="davon Cache geschrieben (1 Std.)"
                    ),
                ),
                (
                    "reasoning",
                    models.PositiveBigIntegerField(default=0, verbose_name="davon Reasoning"),
                ),
                ("requests", models.PositiveIntegerField(default=0, verbose_name="Anfragen")),
                ("units", models.JSONField(blank=True, default=dict, verbose_name="Einheiten")),
                (
                    "rounds",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Anfragen im Einzelnen"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="Betrag",
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3, verbose_name="Währung")),
                (
                    "amount_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="Betrag (EUR)",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                        verbose_name="Kurs USD->EUR",
                    ),
                ),
                ("rate_date", models.DateField(blank=True, null=True, verbose_name="Kurs vom")),
                (
                    "legacy",
                    models.BooleanField(
                        default=False,
                        help_text="Aus den alten Kosten übernommen (Migration).",
                        verbose_name="aus Bestand",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="billing.billingaccount",
                        verbose_name="Konto",
                    ),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat.aimodel",
                        verbose_name="Modell",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_entries",
                        to="chat.attachment",
                        verbose_name="Anhang",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_entries",
                        to="chat.message",
                        verbose_name="Nachricht",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="billing.modelprice",
                        verbose_name="Preisversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buchung",
                "verbose_name_plural": "Buchungen",
                "ordering": ["-created", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AccountBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nur monetäre Konten. Leer = unbegrenzt.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Monatsbudget (EUR)",
                    ),
                ),
                (
                    "monthly_tokens",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Nur Token-Konten: Eingabe + Ausgabe je Kalendermonat. Leer = unbegrenzt.",
                        null=True,
                        verbose_name="Monatskontingent (Tokens)",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_budgets",
                        to="accounts.role",
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_budgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nutzer",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="billing.billingaccount",
                        verbose_name="Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget je Konto",
                "verbose_name_plural": "Budgets je Konto",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("role__isnull", False), ("user__isnull", True)),
                            models.Q(("role__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="billing_budget_role_xor_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role__isnull", False)),
                        fields=("account", "role"),
                        name="billing_budget_unique_role",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("account", "user"),
                        name="billing_budget_unique_user",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="modelprice",
            constraint=models.UniqueConstraint(
                fields=("ai_model", "valid_from"), name="billing_price_unique_model_valid_from"
            ),
        ),
        migrations.AddIndex(
            model_name="usageentry",
            index=models.Index(fields=["user", "created"], name="billing_entry_user_created"),
        ),
        migrations.AddIndex(
            model_name="usageentry",
            index=models.Index(fields=["account", "created"], name="billing_entry_account_created"),
        ),
        migrations.AddConstraint(
            model_name="usageentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "answer"), ("message__isnull", False)),
                fields=("message",),
                name="billing_entry_unique_answer",
            ),
        ),
        migrations.AddConstraint(
            model_name="usageentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attachment__isnull", False), ("kind", "attachment")),
                fields=("attachment",),
                name="billing_entry_unique_attachment",
            ),
        ),
    ]
