# Generated by Django 5.2.18 on 2026-10-09 19:29

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0013_job_retry"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionProxy",
            fields=[],
            options={
                "verbose_name": "Sammlung",
                "verbose_name_plural": "Sammlungen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chat.collection",),
        ),
        migrations.CreateModel(
            name="DocumentProxy",
            fields=[],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumente",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chat.document",),
        ),
        migrations.CreateModel(
            name="JobProxy",
            fields=[],
            options={
                "verbose_name": "Indexierungsauftrag",
                "verbose_name_plural": "Indexierungsaufträge",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chat.job",),
        ),
        migrations.CreateModel(
            name="RagOverview",
            fields=[],
            options={
                "verbose_name": "RAG-Übersicht",
                "verbose_name_plural": "RAG-Übersicht",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chat.ragsettings",),
        ),
        migrations.CreateModel(
            name="RagSettingsProxy",
            fields=[],
            options={
                "verbose_name": "Einstellungen",
                "verbose_name_plural": "Einstellungen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chat.ragsettings",),
        ),
    ]
