# Generated by Django 5.2.18 on 2026-10-09 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_local_rag"),
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectorySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=1000, verbose_name="Verzeichnis")),
                (
                    "recursive",
                    models.BooleanField(default=True, verbose_name="Unterordner einbeziehen"),
                ),
                (
                    "include_patterns",
                    models.CharField(
                        default="*.pdf, *.docx, *.txt, *.md",
                        help_text="Kommagetrennt, z. B. „*.pdf, *.docx“. Nur PDF, DOCX, TXT und MD werden verarbeitet.",
                        max_length=500,
                        verbose_name="Dateimuster",
                    ),
                ),
                (
                    "exclude_patterns",
                    models.CharField(
                        blank=True,
                        default=".*, ~$*, *.tmp, *.part",
                        help_text="Kommagetrennt; gilt für Datei- und Ordnernamen sowie relative Pfade (z. B. „Entwürfe/*“). Versteckte Dateien und Ordner (Name beginnt mit „.“) werden immer übersprungen.",
                        max_length=500,
                        verbose_name="Ausschlussmuster",
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Wie oft das Verzeichnis eingelesen wird (mindestens 5).",
                        validators=[django.core.validators.MinValueValidator(5)],
                        verbose_name="Intervall (Minuten)",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "last_scan_started",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="letzter Lauf begonnen"
                    ),
                ),
                (
                    "last_scan_finished",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="letzter Lauf beendet"
                    ),
                ),
                (
                    "last_result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ergebnis des letzten Laufs"
                    ),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="letzter Fehler")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="angelegt")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directory_sources",
                        to="chat.collection",
                        verbose_name="Sammlung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verzeichnisquelle",
                "verbose_name_plural": "Verzeichnisquellen",
                "ordering": ["collection__name", "pk"],
            },
        ),
    ]
