# Generated by Django 5.2.18 on 2026-10-09 22:43

"""Proxy „Läufe“ für den Admin-Abschnitt „Dokumente (RAG)“ (keine Tabelle)."""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0017_index_runs"),
        ("rag", "0002_directorysource"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexRunProxy",
            fields=[],
            options={
                "verbose_name": "Lauf",
                "verbose_name_plural": "Läufe",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chat.indexrun",),
        ),
    ]
