# Generated by Django 5.2.18 on 2026-10-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag", "0003_index_runs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directorysource",
            name="include_patterns",
            field=models.CharField(
                default="*.pdf, *.docx, *.txt, *.md",
                help_text="Kommagetrennt, z. B. „*.pdf, *.docx“. Verarbeitet werden PDF, DOCX, TXT, MD und Bilddateien (JPG, PNG, TIFF, WEBP); Bilder nur, wenn ein Muster sie einschließt (z. B. „*.jpg, *.png“) – jedes Bild kostet OCR und ggf. einen Modellaufruf.",
                max_length=500,
                verbose_name="Dateimuster",
            ),
        ),
    ]
